### ISSUE TITLE
Thanks for style guide...

### ISSUE THREAD

**Issue by Laurence-Technologist** [CarmenPopoviciu/protractor-testing-guidelines#19]
Hi,

I am using Protractor.
I saw the video and just read through the very useful README.

Just a suggestion...

10 occurrences of styleguide should read as 2 words: style guide

Looking forward to reading the next updates.

Regards,
lgsoftwareqa.

**Comment by CarmenPopoviciu** [comment]
Hey @lgsoftwareqa,

Very happy to hear this was useful for you ^_^. Do you want to send a pull request for the issue you just mentioned ;)?

**Comment by robinj** [comment]
@lgsoftwareqa, @CarmenPopoviciu proposing to rename all instances of "Protractor Styleguide" to "Protractor style guide", as per https://github.com/styleguide or https://www.theguardian.com/guardian-observer-style-guide-a if there are no objections then I will send a PR through shortly.
