### ISSUE TITLE
Please advice independent tests

### ISSUE THREAD

**Issue by nicojs** [CarmenPopoviciu/protractor-testing-guidelines#20]
I'm happy to see that the protractor style guide is getting some traction! However, as you might know already, i do not agree with the explanation of Rule-23. In there, it specifies that you can make your tests depend on each other when you might end up with too high test run times. I think you should, at the very least, be able to run each test independent (as a focused test (_fit_) for example). 

However, i do understand the need for fast running ui tests. So I would like to propose an alternative. What about using the jasmine beforeAll function (instead of beforeEach) to navigate to the correct page (or do other time intensive stuff). In this way, you can still run each test independent, while also having the performance gain. 

The example would change into something like this:

``` javascript
describe('when the user Teddy B is created', function(){
    beforeAll(function(){
       browser.get('#/user-list');
       userList.newButton.click();

       userProperties.name.sendKeys('Teddy B');
       userProperties.saveButton.click();
       browser.get('#/user-list');
    });

    it('should exist', function(){
       userList.search('Teddy B');
       expect(userList.getNames()).toEqual(['Teddy B']);    
       userList.clear();
    });

    describe('and gets updated to Teddy C', function(){

        beforeAll(function(){
            userList.clickOn('Teddy B');

            userProperties.name.clear().sendKeys('Teddy C');
            userProperties.saveButton.click();

            browser.get('#/user-list');
        });

        it('should be Teddy C', function(){
            userList.search('Teddy C');
            expect(userList.getNames()).toEqual(['Teddy C']);
            userList.clear();
        });
    });
});
```

If you agree, i would be happy to create a pull-request for this issue.

**Comment by CarmenPopoviciu** [comment]
Yes!! I think this is a very clean solution to the exception that Rule-23 addresses. I like it! I like it a lot! If u have time for the pull request, go for it!

I also think we could then split the rule in two: one for best, non expensive scenarios, and one for the exception. Jasmine's 'beforeAll()' is quite powerful. It should get a bit more love in the styleguide

Thank you for the raising the issue. Very cool to see you're still guarding the project <3

**Comment by LayZeeDK** [comment]
Seeing that #21 addresses it, this issue can be closed.
