### ISSUE TITLE
Require all for page objects

### ISSUE THREAD

**Issue by wlsf82** [CarmenPopoviciu/protractor-testing-guidelines#23]
Hey Carmen,

Do you think would be a good pattern to have something like a require all of the page objects in the protractor's configuration file, so that all page objects are globally available for usage for any test (spec file).

In some projects I've been working we do something like this, and I would know if it could be considered a anti-pattern. If not, I would like to contribute with this. Is this possible?

Since then I appreciate your help.

**Comment by Occimetric** [comment]
I want to add my two cents, if you want to run just some test, and the creation of the all page objects take a while, I think that could be a pain in the neck, IMHO, everything in software should use the minimum artifacts that are required to work.
