### ISSUE TITLE
Type Over in code -  documentation

### ISSUE THREAD

**Issue by arung86** [CarmenPopoviciu/protractor-testing-guidelines#25]
In documentaion, 
section: https://github.com/CarmenPopoviciu/protractor-styleguide#rule-13-declare-one-page-object-per-file, There is a type over in the module being exported. UserPropertiesPage module have been exported instead of UserProfilePage, both in the recommended and to be avoided sections.

**Comment by sukrosono** [comment]
let's wait when this got merged.

**Comment by robinj** [comment]
Fixed in #28
