### ISSUE TITLE
This project may need an additional maintainer

### ISSUE THREAD

**Issue by robinj** [CarmenPopoviciu/protractor-testing-guidelines#27]
Hi @CarmenPopoviciu 

I watched your talk about this style guide at Angular Connect 2015 and feel that this is a great resource for people getting started with writing Protractor tests. We are currently linking to parts of it in our internal documentation about end to end testing.

The repo invites people to contribute but there are a number of open issues and pull requests which have not been addressed in a long while. Perhaps you are busy, but it would be great if there were one or two additional people with access to merge pull requests and close issues to make sure that the advice in this guide doesn't become too stale. 

Thanks for this valuable resource!

**Comment by alecxe** [comment]
@CarmenPopoviciu @robinj if you guys need help maintaining the project, I'd be happy to help with it. Let me know, thanks.

**Comment by CarmenPopoviciu** [comment]
@robinj you are very right. I've been meaning to give this project more love since ages, but unfortunately there was never enough time :(. It would indeed be great to get someone else on board who can share responsibility of maintaining it. I'm going to reach out to the community and see if anyone is interested

**Comment by CarmenPopoviciu** [comment]
@alecxe ^5. What is the best way to reach you?

**Comment by robinj** [comment]
@CarmenPopoviciu I am interested in helping to get some of these pull requests reviewed and merged and trying to close some of the issues. I use it quite heavily in the organisation that I work for so can dedicate some of my time towards it.

**Comment by alecxe** [comment]
@CarmenPopoviciu probably having a gitter chat for the CarmenPopoviciu/protractor-styleguide github project would be the best way to communicate for all of us. I'm also okay with hangouts, skype, slack etc. What do you think?

**Comment by CarmenPopoviciu** [comment]
done: https://gitter.im/protractor-styleguide

**Comment by robinj** [comment]
Closing this issue as we now have three maintainers

**Comment by LayZeeDK** [comment]
No issues have been closed since the additional maintainers have been added. What a pity.

**Comment by robinj** [comment]
@layzeedk you are free to raise PRs. I have reviewed some but then the submitters didn't respond to change requests.

**Comment by LayZeeDK** [comment]
Thank you for getting back to me, @robinj. I have created #40.
