### ISSUE TITLE
Add protractor conf best practices section

### ISSUE THREAD

**Issue by CarmenPopoviciu** [CarmenPopoviciu/protractor-testing-guidelines#7]

**Comment by nicojs** [comment]
Oops, I checked in on the master branche! It won’t happen again. 
@CarmenPopoviciu can you review the text?

**Comment by CarmenPopoviciu** [comment]
I am not in today, doing a course, but will check in a bit :)

**Comment by CarmenPopoviciu** [comment]
Ok, I just checked. Looks good, there is one typo but I'll fix that. I'm
still on my phone now.

Did u have time to read the rest? What do u think so far? Please feel free
to make any suggestions or pull requests on it. I am more than open to it :)
